### ISSUE TITLE
Argument 1 passed to Grav\Plugin\Cadphp\Cadphp::process() must be an instance of Grav\Plugin\Cadphp\String, string given, 

### ISSUE THREAD

**Issue by matto3c** [cadjou/grav-plugin-cadphp#1]
Hi,
great plugin and exactly what I was looking for.

got this error on PHP 5.6.39 (should probably work on PHP >=7.2), 
simple solution how to change it quickly in the code is to remove the "String" type from method in Cadphp.php

	public function process(String $content)

and make it

	public function process($content)

as well as

	public function calculPhp(String &$content)

change it to:

	public function calculPhp(&$content)

**Comment by cadjou** [comment]
Hello, and thank you to use this plugin.
I add some change about your issue.
Enjoy the the version 1.0.2 ;)

**Comment by matto3c** [comment]
Hi cadjou,
one remark though. While debugging the code, I tried to figure out how it works and everything mostly clear, but some variables are in french, and I'm not sure what it's supposed to mean:

// racin path in depend of the beginning of the Predefined Path (Absolu or Relative Path)
					$racin	= ???

At the end I've ended up writing my own grav plugin. Grav great. Take care.
