### ISSUE TITLE
Need support for plugin use

### ISSUE THREAD

**Issue by andrea75** [cadjou/grav-plugin-cadphp#3]
Hi, I'm new in GRAV, and maybe I have to still learning a lot. I needed a plugin to insert a PHP code on my pages, nad finally I find this plugin!
But now the problem is to understand how to use it. The plugin is installed and active. But or I wrong something, or maybe, I don't understand well when I have to place the code.
I made a blank page, withount any content, and I place 

`cadphp:p1:test`

at the begin of the default.md file on the new page folder created. But nothing happen... the text "hello world" doesn't appear. Where I wrong? :(

**Comment by cadjou** [comment]
Hello @andrea75 , to use cadphp, after installation, you have to save the parameters in the plugin interface if you have admin interface or copy the file cadphp.yaml in /user/config/plugins/cadphp.yml with this minimum :
enabled: true
p1: php/

after you can put cadphp:p1:test where you want in your page.

Let me know if it's working.

Bye

**Comment by andrea75** [comment]
I missed this step! Now it working like a charm! :) Thank you so much
